import {
  Avatar,
  Container,
  Flex,
  Heading,
  List,
  ListItem,
  Text,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import GymManagerLayout from "../components/layouts/GymManagerLayout";
import OtpScreen from "../components/OtpScreen/OtpScreen";
import QRScanner from "../components/QRScanner/QRScanner";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <OtpScreen /> */}
      <GymManagerLayout>
        <Container>
          <Heading as="h4" color="tomato">
            Attendance Today
          </Heading>
          <List spacing={3} overflow="scroll" height="90vh">
            <ListItem>
              <Flex alignItems="center">
                <Avatar name="Dan Abrahmov" src="https://bit.ly/dan-abramov" />
                <Flex ml="3" justifyContent="space-between" w="100%">
                  <Flex direction="column">
                    <Text fontWeight="bold">Satish</Text>
                    <Text fontSize="10px">8130626713</Text>
                    <Text fontSize="10px">
                      Membership expired on 31st Dec 2021
                    </Text>
                  </Flex>
                  <Text fontSize="12px">12:47PM</Text>
                </Flex>
              </Flex>
            </ListItem>
            <ListItem>
              <Avatar
                name="Kola Tioluwani"
                src="https://bit.ly/tioluwani-kolawole"
              />
              <Text>Satish</Text>
            </ListItem>
            <ListItem>
              <Avatar name="Dan Abrahmov" src="https://bit.ly/dan-abramov" />
            </ListItem>
            <ListItem>
              <Avatar
                name="Kola Tioluwani"
                src="https://bit.ly/tioluwani-kolawole"
              />
            </ListItem>
            <ListItem>
              <Avatar name="Dan Abrahmov" src="https://bit.ly/dan-abramov" />
            </ListItem>
            <ListItem>
              <Avatar
                name="Kola Tioluwani"
                src="https://bit.ly/tioluwani-kolawole"
              />
            </ListItem>
            <ListItem>
              <Avatar name="Dan Abrahmov" src="https://bit.ly/dan-abramov" />
            </ListItem>
            <ListItem>
              <Avatar
                name="Kola Tioluwani"
                src="https://bit.ly/tioluwani-kolawole"
              />
            </ListItem>
            <ListItem>
              <Avatar name="Dan Abrahmov" src="https://bit.ly/dan-abramov" />
            </ListItem>
            <ListItem>
              <Avatar
                name="Kola Tioluwani"
                src="https://bit.ly/tioluwani-kolawole"
              />
            </ListItem>
            <ListItem>
              <Avatar name="Dan Abrahmov" src="https://bit.ly/dan-abramov" />
            </ListItem>
            <ListItem>
              <Avatar
                name="Kola Tioluwani"
                src="https://bit.ly/tioluwani-kolawole"
              />
            </ListItem>
            <ListItem>
              <Avatar name="Dan Abrahmov" src="https://bit.ly/dan-abramov" />
            </ListItem>
            <ListItem>
              <Avatar
                name="Kola Tioluwani"
                src="https://bit.ly/tioluwani-kolawole"
              />
            </ListItem>
            <ListItem>
              <Avatar name="Dan Abrahmov" src="https://bit.ly/dan-abramov" />
            </ListItem>
            <ListItem>
              <Avatar
                name="Kola Tioluwani"
                src="https://bit.ly/tioluwani-kolawole"
              />
            </ListItem>
          </List>
        </Container>
      </GymManagerLayout>
    </div>
  );
};

export default Home;
